PersonaBundle\Entity\User:
    type: mappedSuperclass
    table: "`user`"
    repositoryClass: PersonaBundle\Repository\UserRepository
    fields:
        email:
            column: email
            type: string
            length: 255
            unique: true
            nullable: false

        username:
            column: username
            type: string
            length: 255
            unique: true
            nullable: false

        password:
            column: password
            type: string
            length: 255
            unique: false
            nullable: false

        roles:
            column: roles
            type: array
            unique: false
            nullable: true