CuteNinja\PersonaBundle\Entity\AbstractUser:
    type: mappedSuperclass
    table: "`user`"
    repositoryClass: CuteNinja\PersonaBundle\Repository\UserRepository
    fields:
        email:
            column: email
            type: string
            length: 255
            unique: true
            nullable: false

        username:
            column: username
            type: string
            length: 255
            unique: true
            nullable: false

        password:
            column: password
            type: string
            length: 255
            unique: false
            nullable: false

        roles:
            column: roles
            type: array
            unique: false
            nullable: true

        status:
            column: status
            type: string
            columnDefinition: ENUM('active', 'inactive')
            scale: 0
            length: 25
            unique: false
            nullable: false
            precision: 0

        createdAt:
            column: created_at
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0

        updatedAt:
            column: updated_at
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0

    lifecycleCallbacks:
        prePersist: [logCreation]
        preUpdate: [logUpdate]