CuteNinja\PersonaBundle\Entity\AbstractUser:
    type: mappedSuperclass
    repositoryClass: CuteNinja\PersonaBundle\Repository\UserRepository
    fields:
        username:
            column: username
            type: string
            length: 100
            unique: true
            nullable: false

        email:
            column: email
            type: string
            length: 255
            unique: true
            nullable: false

        salt:
            column: salt
            type: string
            length: 255
            unique: false
            nullable: false

        password:
            column: password
            type: string
            length: 255
            unique: false
            nullable: false

        firstName:
            column: first_name
            type: string
            length: 150
            unique: false
            nullable: false

        lastName:
            column: last_name
            type: string
            length: 150
            unique: false
            nullable: false

        avatar:
            column: avatar
            type: string
            length: 255
            unique: false
            nullable: false

        lastConnectedAt:
            column: last_connected_at
            type: datetime
            unique: false
            nullable: true