CuteNinja\PersonaBundle\Entity\Role:
    type: entity
    table: "`role`"
    repositoryClass: CuteNinja\PersonaBundle\Repository\RoleRepository
    id:
        value:
            type: string
            length: 75
            unique: true
            nullable: false
            id: true
            generator:
                strategy: NONE

    fields:
        label:
            column: email
            type: string
            length: 255
            unique: true
            nullable: false

        description:
            column: description
            type: text
            unique: false
            nullable: true