PersonaBundle\Entity\User:
    type: mappedSuperclass
    table: "`user`"
    repositoryClass: PersonaBundle\Repository\UserRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY

    fields:
        email:
            column: email
            type: string
            length: 255
            unique: true
            nullable: false

        username:
            column: username
            type: string
            length: 255
            unique: true
            nullable: false

        password:
            column: password
            type: string
            length: 255
            unique: false
            nullable: false

        roles:
            column: roles
            type: array
            unique: false
            nullable: true